# Generated by Django 3.2.13 on 2022-05-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intTime', models.BigIntegerField()),
                ('token', models.CharField(max_length=10)),
                ('price', models.FloatField()),
            ],
        ),
    ]
