# Generated by Django 4.0.4 on 2022-05-19 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_Pass_Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200, null=True)),
                ('secretInt', models.BigIntegerField(default=238123, null=True)),
                ('newPassword', models.CharField(default='', max_length=50, null=True)),
                ('username_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password_Change_Requests',
            },
        ),
    ]
