version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: build
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
