# Generated by Django 4.0.4 on 2022-04-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
                ('price_per_coin', models.FloatField()),
            ],
        ),
    ]
