# Generated by Django 4.0.4 on 2022-05-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_positions',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='acc_positions',
            name='coin',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='acc_positions',
            name='price_per_coin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='acc_positions',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
