# Generated by Django 4.0.4 on 2022-05-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0005_coins_alter_acc_positions_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='ticker',
            field=models.CharField(choices=[('PLS', 'PLS'), ('HEX', 'HEX'), ('PLSX', 'PLSX')], max_length=4, null=True),
        ),
    ]
