# Generated by Django 4.0.4 on 2022-05-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0006_alter_coins_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acc_positions',
            options={'verbose_name_plural': 'ACC_Positions'},
        ),
        migrations.AlterModelOptions(
            name='coins',
            options={'verbose_name_plural': 'Coins'},
        ),
    ]
