# Generated by Django 4.0.4 on 2022-05-06 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackapp', '0007_alter_acc_positions_options_alter_coins_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_positions',
            name='username_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='acc_positions',
            name='coin',
        ),
        migrations.AddField(
            model_name='acc_positions',
            name='coin',
            field=models.ManyToManyField(to='trackapp.coins'),
        ),
    ]
