# Generated by Django 4.0.4 on 2022-05-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0009_alter_acc_positions_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc_positions',
            name='coin',
        ),
        migrations.AddField(
            model_name='acc_positions',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackapp.coins'),
        ),
    ]
