# Generated by Django 4.0.4 on 2022-05-17 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackapp', '0013_alter_acc_positions_coin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_positions',
            name='coin',
            field=models.CharField(choices=[('PLS', 'PLS'), ('HEX', 'HEX'), ('PLSX', 'PLSX')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='acc_positions',
            name='username_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
