# Generated by Django 3.2.13 on 2022-05-22 20:06

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0014_alter_acc_positions_coin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_positions',
            name='time_bought',
            field=models.BigIntegerField(default=time.time, null=True),
        ),
    ]
