# Generated by Django 3.2.13 on 2022-05-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0015_acc_positions_time_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc_positions',
            name='time_bought',
        ),
    ]
