# Generated by Django 3.2.13 on 2022-05-23 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0017_acc_positions_time_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_positions',
            name='time_bought',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
