# Generated by Django 4.0.5 on 2022-06-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0019_alter_acc_positions_coin_alter_coinprices_symbol_and_more'),
        ('trackapp', '0019_auto_20220530_2011'),
    ]

    operations = [
    ]
