# Generated by Django 4.0.5 on 2022-06-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0020_merge_20220628_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_positions',
            name='coin',
            field=models.CharField(choices=[('HEX', 'HEX'), ('PLS', 'PLS'), ('PLSX', 'PLSX'), ('eETH', 'eETH'), ('DAI', 'DAI'), ('INC', 'INC'), ('USDC', 'USDC'), ('USDT', 'USDT')], default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='ticker',
            field=models.CharField(choices=[('HEX', 'HEX'), ('PLS', 'PLS'), ('PLSX', 'PLSX'), ('eETH', 'eETH'), ('DAI', 'DAI'), ('INC', 'INC'), ('USDC', 'USDC'), ('USDT', 'USDT')], max_length=8, null=True),
        ),
    ]
