# Generated by Django 3.2.13 on 2022-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0021_alter_acc_positions_coin_alter_coins_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_positions',
            name='coin',
            field=models.CharField(default='', max_length=8, null=True),
        ),
    ]
