# Generated by Django 3.2.13 on 2022-07-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0022_alter_acc_positions_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_positions',
            name='wallet',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='acc_positions',
            name='coin',
            field=models.CharField(choices=[('HEX', 'HEX'), ('PLS', 'PLS'), ('PLSX', 'PLSX'), ('eETH', 'eETH'), ('DAI', 'DAI'), ('INC', 'INC'), ('USDC', 'USDC'), ('USDT', 'USDT')], default='', max_length=8, null=True),
        ),
    ]
